travis:
  secure:
    BINSTAR_TOKEN: WDcY5a4Ti9tKFA3O6vXK34S4KljvFRugq7thTdDD6kZnfIOIUTvOTiRHsJxwpAvtm8/P9JuWHm5wKoI5G5M5SiOMIiW/rorgZEzOIx7QrKfM7UfYCIE3D8rF4V7rXFkIQjWUg8kmRWoYjcCkrFV4mRjG78N2MeI+ZMNlW2ISVAfDTS96XaCt92ByWPaDaPYntYHPipw0d4pkKA7slGnN/IVLSIbjF7CxblwPPYY800qeWShCGDh8kFxx25SoL8/AY5ogrsUgZuA9mbZImjOkLbO3vcvhzYJyqi+NxSDfx+o0ogEMrFYY1p74WgMZdPecJYSovgp78Iy98LeVSYHPphzFNG/IeyR65HGgkqWRQDDKkQIG6MGuMVo9W+owea7ocwGTHRLUjKk6lYjhlqVhV7oAxQVADK4UQoy8+z6OAmUCpDd7njdgYZQU+oYhgeblUaBtSBu1QKvPP5ayyVq0wVcs45JghfGLYYk2G9HrDxZW5H3Mp4M0SQSehPi2SGOaqgE1Pf+D9lnt0LUUjGylzzBDGMWKFGV1VwSk8lPrK0E6EsvXQv2pYgQ9l7/lFlv1F3BWDNhG83bHzoFdeDDzS5yIM+QcLS/L87ptbEVbCWHNWgCmoxD0p/9h3rBJAn1Gw9iyqnORfz+d5P78zAQIdpLWHemeSahvS5dyyCar6C4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
